Catalog: trick to get date working althouth the whole column is NULL:
    BIG BUG in CachedRowSet: if one sets all values in a column to NULL and then
    serializes the CachedRowSet then deserializing and attempting an update
    would result in an Exception where apparently the column type is not being
    set so defaults to the type of the prior column:

    org.postgresql.util.PSQLException: ERROR column "fecha_actualizacion" is of
    type character varying but expression is of type Date

    See info here:
    http://books.google.es/books?id=4yjiwDMmOZMC&lpg=PA232&ots=9yQFXXfd5H&pg=PA232#v=onepage&q&f=false

    So, the trick we do here is: in case the date is NULL, set it to first
    milisecond from epoch (1970-01-01). When reading back from database will
    check if the data is higher than this and, if not, will return a NULL. See
    EventosRecordsetAdapter.getDate()